/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiErrorData = {
    message: string;
};

export class ApiError extends Error {
    /** The original data that was passed to this error instance. */
    data$: ApiErrorData;

    constructor(err: ApiErrorData) {
        super("");
        this.data$ = err;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "ApiError";
    }
}

/** @internal */
export namespace ApiError$ {
    export const inboundSchema: z.ZodType<ApiError, z.ZodTypeDef, unknown> = z
        .object({
            message: z.string(),
        })
        .transform((v) => {
            return new ApiError(v);
        });

    export type Outbound = {
        message: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApiError> = z
        .instanceof(ApiError)
        .transform((v) => v.data$)
        .pipe(
            z.object({
                message: z.string(),
            })
        );
}
