/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appsV1CreateAppV1Deprecated } from "../../funcs/appsV1CreateAppV1Deprecated.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AppConfig$inboundSchema,
};

export const tool$appsV1CreateAppV1Deprecated: ToolDefinition<typeof args> = {
  name: "apps-v1_create-app-v1-deprecated",
  description: `CreateAppV1Deprecated

Create a new [application](https://hathora.dev/docs/concepts/hathora-entities#application).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await appsV1CreateAppV1Deprecated(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
