/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { managementV1SendVerificationEmail } from "../../funcs/managementV1SendVerificationEmail.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.VerificationEmailRequest$inboundSchema,
};

export const tool$managementV1SendVerificationEmail: ToolDefinition<
  typeof args
> = {
  name: "management-v1-send-verification-email",
  description: `SendVerificationEmail`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await managementV1SendVerificationEmail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
