/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { organizationsV1RejectInvite } from "../../funcs/organizationsV1RejectInvite.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  orgId: z.string(),
};

export const tool$organizationsV1RejectInvite: ToolDefinition<typeof args> = {
  name: "organizations-v1_reject-invite",
  description: `RejectInvite`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationsV1RejectInvite(
      client,
      args.orgId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
