/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { roomsV2GetConnectionInfo } from "../../funcs/roomsV2GetConnectionInfo.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  roomId: z.string(),
  appId: z.string().optional(),
};

export const tool$roomsV2GetConnectionInfo: ToolDefinition<typeof args> = {
  name: "rooms-v2-get-connection-info",
  description: `GetConnectionInfo

Poll this endpoint to get connection details to a [room](https://hathora.dev/docs/concepts/hathora-entities#room). Clients can call this endpoint without authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await roomsV2GetConnectionInfo(
      client,
      args.roomId,
      args.appId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
