/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetMetricsSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    auth0: string;
}

export class GetMetricsRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=appId" })
    appId: string;

    /**
     * Unix timestamp. Default is current time.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=end" })
    end?: number;

    /**
     * Available metrics to query over time.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=metrics" })
    metrics?: shared.MetricName[];

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=processId" })
    processId: string;

    /**
     * Unix timestamp. Default is -1 hour from `end`.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=start" })
    start?: number;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=step" })
    step?: number;
}

export class GetMetricsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    getMetrics404ApplicationJSONString?: string;

    @SpeakeasyMetadata()
    getMetrics422ApplicationJSONString?: string;

    /**
     * Ok
     */
    @SpeakeasyMetadata()
    metricsResponse?: shared.MetricsResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
