workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://hathora.dev/swagger.json
        registry:
            location: registry.speakeasyapi.dev/hathora/hathora/my-source
targets:
    hathora-typescript:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
        codeSamples:
            output: .speakeasy/codeSamples.yaml
