/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AcceptInviteRequest = {
  orgId: string;
};

/** @internal */
export type AcceptInviteRequest$Outbound = {
  orgId: string;
};

/** @internal */
export const AcceptInviteRequest$outboundSchema: z.ZodType<
  AcceptInviteRequest$Outbound,
  z.ZodTypeDef,
  AcceptInviteRequest
> = z.object({
  orgId: z.string(),
});

export function acceptInviteRequestToJSON(
  acceptInviteRequest: AcceptInviteRequest,
): string {
  return JSON.stringify(
    AcceptInviteRequest$outboundSchema.parse(acceptInviteRequest),
  );
}
