/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type CreateDeploymentGlobals = {
    appId?: string | undefined;
};

export type CreateDeploymentRequest = {
    appId?: string | undefined;
    buildId: number;
    deploymentConfigV2: components.DeploymentConfigV2;
};

/** @internal */
export namespace CreateDeploymentGlobals$ {
    export const inboundSchema: z.ZodType<CreateDeploymentGlobals, z.ZodTypeDef, unknown> =
        z.object({
            appId: z.string().optional(),
        });

    export type Outbound = {
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateDeploymentGlobals> =
        z.object({
            appId: z.string().optional(),
        });
}

/** @internal */
export namespace CreateDeploymentRequest$ {
    export const inboundSchema: z.ZodType<CreateDeploymentRequest, z.ZodTypeDef, unknown> = z
        .object({
            appId: z.string().optional(),
            buildId: z.number().int(),
            DeploymentConfigV2: components.DeploymentConfigV2$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                DeploymentConfigV2: "deploymentConfigV2",
            });
        });

    export type Outbound = {
        appId?: string | undefined;
        buildId: number;
        DeploymentConfigV2: components.DeploymentConfigV2$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateDeploymentRequest> = z
        .object({
            appId: z.string().optional(),
            buildId: z.number().int(),
            deploymentConfigV2: components.DeploymentConfigV2$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                deploymentConfigV2: "DeploymentConfigV2",
            });
        });
}
