/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateFleetGlobals = {
  orgId?: string | undefined;
};

export type CreateFleetRequest = {
  orgId?: string | undefined;
  createFleetV2: components.CreateFleetV2;
};

/** @internal */
export type CreateFleetRequest$Outbound = {
  orgId?: string | undefined;
  CreateFleetV2: components.CreateFleetV2$Outbound;
};

/** @internal */
export const CreateFleetRequest$outboundSchema: z.ZodType<
  CreateFleetRequest$Outbound,
  z.ZodTypeDef,
  CreateFleetRequest
> = z.object({
  orgId: z.string().optional(),
  createFleetV2: components.CreateFleetV2$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createFleetV2: "CreateFleetV2",
  });
});

export function createFleetRequestToJSON(
  createFleetRequest: CreateFleetRequest,
): string {
  return JSON.stringify(
    CreateFleetRequest$outboundSchema.parse(createFleetRequest),
  );
}
