/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateAppGlobals = {
  orgId?: string | undefined;
};

export type CreateAppRequest = {
  orgId?: string | undefined;
  createAppConfig: components.CreateAppConfig;
};

/** @internal */
export type CreateAppRequest$Outbound = {
  orgId?: string | undefined;
  CreateAppConfig: components.CreateAppConfig$Outbound;
};

/** @internal */
export const CreateAppRequest$outboundSchema: z.ZodType<
  CreateAppRequest$Outbound,
  z.ZodTypeDef,
  CreateAppRequest
> = z.object({
  orgId: z.string().optional(),
  createAppConfig: components.CreateAppConfig$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createAppConfig: "CreateAppConfig",
  });
});

export function createAppRequestToJSON(
  createAppRequest: CreateAppRequest,
): string {
  return JSON.stringify(
    CreateAppRequest$outboundSchema.parse(createAppRequest),
  );
}
