/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateBuildWithUploadUrlV2DeprecatedGlobals = {
  appId?: string | undefined;
};

export type CreateBuildWithUploadUrlV2DeprecatedRequest = {
  appId?: string | undefined;
  createBuildParams: components.CreateBuildParams;
};

/** @internal */
export type CreateBuildWithUploadUrlV2DeprecatedRequest$Outbound = {
  appId?: string | undefined;
  CreateBuildParams: components.CreateBuildParams$Outbound;
};

/** @internal */
export const CreateBuildWithUploadUrlV2DeprecatedRequest$outboundSchema:
  z.ZodType<
    CreateBuildWithUploadUrlV2DeprecatedRequest$Outbound,
    z.ZodTypeDef,
    CreateBuildWithUploadUrlV2DeprecatedRequest
  > = z.object({
    appId: z.string().optional(),
    createBuildParams: components.CreateBuildParams$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      createBuildParams: "CreateBuildParams",
    });
  });

export function createBuildWithUploadUrlV2DeprecatedRequestToJSON(
  createBuildWithUploadUrlV2DeprecatedRequest:
    CreateBuildWithUploadUrlV2DeprecatedRequest,
): string {
  return JSON.stringify(
    CreateBuildWithUploadUrlV2DeprecatedRequest$outboundSchema.parse(
      createBuildWithUploadUrlV2DeprecatedRequest,
    ),
  );
}
