/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DownloadLogForProcessGlobals = {
    appId?: string | undefined;
};

export type DownloadLogForProcessRequest = {
    appId?: string | undefined;
    processId: string;
};

/** @internal */
export namespace DownloadLogForProcessGlobals$ {
    export const inboundSchema: z.ZodType<DownloadLogForProcessGlobals, z.ZodTypeDef, unknown> =
        z.object({
            appId: z.string().optional(),
        });

    export type Outbound = {
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadLogForProcessGlobals> =
        z.object({
            appId: z.string().optional(),
        });
}

/** @internal */
export namespace DownloadLogForProcessRequest$ {
    export const inboundSchema: z.ZodType<DownloadLogForProcessRequest, z.ZodTypeDef, unknown> =
        z.object({
            appId: z.string().optional(),
            processId: z.string(),
        });

    export type Outbound = {
        appId?: string | undefined;
        processId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadLogForProcessRequest> =
        z.object({
            appId: z.string().optional(),
            processId: z.string(),
        });
}
