/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetAppInfoV1DeprecatedGlobals = {
  appId?: string | undefined;
};

export type GetAppInfoV1DeprecatedRequest = {
  appId?: string | undefined;
};

/** @internal */
export type GetAppInfoV1DeprecatedRequest$Outbound = {
  appId?: string | undefined;
};

/** @internal */
export const GetAppInfoV1DeprecatedRequest$outboundSchema: z.ZodType<
  GetAppInfoV1DeprecatedRequest$Outbound,
  z.ZodTypeDef,
  GetAppInfoV1DeprecatedRequest
> = z.object({
  appId: z.string().optional(),
});

export function getAppInfoV1DeprecatedRequestToJSON(
  getAppInfoV1DeprecatedRequest: GetAppInfoV1DeprecatedRequest,
): string {
  return JSON.stringify(
    GetAppInfoV1DeprecatedRequest$outboundSchema.parse(
      getAppInfoV1DeprecatedRequest,
    ),
  );
}
