/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetActiveRoomsForProcessDeprecatedGlobals = {
  appId?: string | undefined;
};

export type GetActiveRoomsForProcessDeprecatedRequest = {
  appId?: string | undefined;
  processId: string;
};

/** @internal */
export type GetActiveRoomsForProcessDeprecatedRequest$Outbound = {
  appId?: string | undefined;
  processId: string;
};

/** @internal */
export const GetActiveRoomsForProcessDeprecatedRequest$outboundSchema:
  z.ZodType<
    GetActiveRoomsForProcessDeprecatedRequest$Outbound,
    z.ZodTypeDef,
    GetActiveRoomsForProcessDeprecatedRequest
  > = z.object({
    appId: z.string().optional(),
    processId: z.string(),
  });

export function getActiveRoomsForProcessDeprecatedRequestToJSON(
  getActiveRoomsForProcessDeprecatedRequest:
    GetActiveRoomsForProcessDeprecatedRequest,
): string {
  return JSON.stringify(
    GetActiveRoomsForProcessDeprecatedRequest$outboundSchema.parse(
      getActiveRoomsForProcessDeprecatedRequest,
    ),
  );
}
