/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetBuildInfoDeprecatedGlobals = {
    appId?: string | undefined;
};

export type GetBuildInfoDeprecatedRequest = {
    appId?: string | undefined;
    buildId: number;
};

/** @internal */
export namespace GetBuildInfoDeprecatedGlobals$ {
    export const inboundSchema: z.ZodType<GetBuildInfoDeprecatedGlobals, z.ZodTypeDef, unknown> =
        z.object({
            appId: z.string().optional(),
        });

    export type Outbound = {
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBuildInfoDeprecatedGlobals> =
        z.object({
            appId: z.string().optional(),
        });
}

/** @internal */
export namespace GetBuildInfoDeprecatedRequest$ {
    export const inboundSchema: z.ZodType<GetBuildInfoDeprecatedRequest, z.ZodTypeDef, unknown> =
        z.object({
            appId: z.string().optional(),
            buildId: z.number().int(),
        });

    export type Outbound = {
        appId?: string | undefined;
        buildId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBuildInfoDeprecatedRequest> =
        z.object({
            appId: z.string().optional(),
            buildId: z.number().int(),
        });
}
