/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetDeploymentInfoRequest = {
    deploymentId: number;
    appId?: string | undefined;
};

/** @internal */
export namespace GetDeploymentInfoRequest$ {
    export type Inbound = {
        deploymentId: number;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetDeploymentInfoRequest, z.ZodTypeDef, Inbound> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        deploymentId: number;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDeploymentInfoRequest> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}
