/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetFleetsRequest = {
  orgId?: string | undefined;
};

/** @internal */
export const GetFleetsRequest$inboundSchema: z.ZodType<
  GetFleetsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  orgId: z.string().optional(),
});

/** @internal */
export type GetFleetsRequest$Outbound = {
  orgId?: string | undefined;
};

/** @internal */
export const GetFleetsRequest$outboundSchema: z.ZodType<
  GetFleetsRequest$Outbound,
  z.ZodTypeDef,
  GetFleetsRequest
> = z.object({
  orgId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFleetsRequest$ {
  /** @deprecated use `GetFleetsRequest$inboundSchema` instead. */
  export const inboundSchema = GetFleetsRequest$inboundSchema;
  /** @deprecated use `GetFleetsRequest$outboundSchema` instead. */
  export const outboundSchema = GetFleetsRequest$outboundSchema;
  /** @deprecated use `GetFleetsRequest$Outbound` instead. */
  export type Outbound = GetFleetsRequest$Outbound;
}
