/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetFleetsDeprecatedGlobals = {
  orgId?: string | undefined;
};

export type GetFleetsDeprecatedRequest = {
  orgId?: string | undefined;
};

/** @internal */
export type GetFleetsDeprecatedRequest$Outbound = {
  orgId?: string | undefined;
};

/** @internal */
export const GetFleetsDeprecatedRequest$outboundSchema: z.ZodType<
  GetFleetsDeprecatedRequest$Outbound,
  z.ZodTypeDef,
  GetFleetsDeprecatedRequest
> = z.object({
  orgId: z.string().optional(),
});

export function getFleetsDeprecatedRequestToJSON(
  getFleetsDeprecatedRequest: GetFleetsDeprecatedRequest,
): string {
  return JSON.stringify(
    GetFleetsDeprecatedRequest$outboundSchema.parse(getFleetsDeprecatedRequest),
  );
}
