/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetInactiveRoomsForProcessGlobals = {
  appId?: string | undefined;
};

export type GetInactiveRoomsForProcessRequest = {
  appId?: string | undefined;
  processId: string;
};

/** @internal */
export type GetInactiveRoomsForProcessRequest$Outbound = {
  appId?: string | undefined;
  processId: string;
};

/** @internal */
export const GetInactiveRoomsForProcessRequest$outboundSchema: z.ZodType<
  GetInactiveRoomsForProcessRequest$Outbound,
  z.ZodTypeDef,
  GetInactiveRoomsForProcessRequest
> = z.object({
  appId: z.string().optional(),
  processId: z.string(),
});

export function getInactiveRoomsForProcessRequestToJSON(
  getInactiveRoomsForProcessRequest: GetInactiveRoomsForProcessRequest,
): string {
  return JSON.stringify(
    GetInactiveRoomsForProcessRequest$outboundSchema.parse(
      getInactiveRoomsForProcessRequest,
    ),
  );
}
