/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetLatestProcessesRequest = {
    appId?: string | undefined;
    status?: Array<components.ProcessStatus> | undefined;
    region?: Array<components.Region> | undefined;
};

/** @internal */
export namespace GetLatestProcessesRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        status?: Array<components.ProcessStatus> | undefined;
        region?: Array<components.Region> | undefined;
    };

    export const inboundSchema: z.ZodType<GetLatestProcessesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            status: z.array(components.ProcessStatus$).optional(),
            region: z.array(components.Region$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        status?: Array<components.ProcessStatus> | undefined;
        region?: Array<components.Region> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLatestProcessesRequest> = z
        .object({
            appId: z.string().optional(),
            status: z.array(components.ProcessStatus$).optional(),
            region: z.array(components.Region$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });
}
