/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetLogsForDeploymentRequest = {
    deploymentId: number;
    appId?: string | undefined;
    follow?: boolean | undefined;
    tailLines?: number | undefined;
};

/** @internal */
export namespace GetLogsForDeploymentRequest$ {
    export type Inbound = {
        deploymentId: number;
        appId?: string | undefined;
        follow?: boolean | undefined;
        tailLines?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForDeploymentRequest, z.ZodTypeDef, Inbound> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
            };
        });

    export type Outbound = {
        deploymentId: number;
        appId?: string | undefined;
        follow: boolean;
        tailLines: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForDeploymentRequest> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
            };
        });
}
