/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetLogsForAppRequest = {
    appId?: string | undefined;
    follow?: boolean | undefined;
    tailLines?: number | undefined;
    region?: components.Region | undefined;
};

/** @internal */
export namespace GetLogsForAppRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        follow?: boolean | undefined;
        tailLines?: number | undefined;
        region?: components.Region | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForAppRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
            region: components.Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        follow: boolean;
        tailLines: number;
        region?: components.Region | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForAppRequest> = z
        .object({
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
            region: components.Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });
}
