/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetOrgTokensRequest = {
  orgId: string;
};

/** @internal */
export type GetOrgTokensRequest$Outbound = {
  orgId: string;
};

/** @internal */
export const GetOrgTokensRequest$outboundSchema: z.ZodType<
  GetOrgTokensRequest$Outbound,
  z.ZodTypeDef,
  GetOrgTokensRequest
> = z.object({
  orgId: z.string(),
});

export function getOrgTokensRequestToJSON(
  getOrgTokensRequest: GetOrgTokensRequest,
): string {
  return JSON.stringify(
    GetOrgTokensRequest$outboundSchema.parse(getOrgTokensRequest),
  );
}
