/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type RejectInviteRequest = {
    orgId: string;
};

/** @internal */
export namespace RejectInviteRequest$ {
    export const inboundSchema: z.ZodType<RejectInviteRequest, z.ZodTypeDef, unknown> = z.object({
        orgId: z.string(),
    });

    export type Outbound = {
        orgId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RejectInviteRequest> = z.object({
        orgId: z.string(),
    });
}
