/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RescindInviteRequest = {
    orgId: string;
    rescindUserInvite: components.RescindUserInvite;
};

/** @internal */
export namespace RescindInviteRequest$ {
    export const inboundSchema: z.ZodType<RescindInviteRequest, z.ZodTypeDef, unknown> = z
        .object({
            orgId: z.string(),
            RescindUserInvite: components.RescindUserInvite$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                RescindUserInvite: "rescindUserInvite",
            });
        });

    export type Outbound = {
        orgId: string;
        RescindUserInvite: components.RescindUserInvite$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RescindInviteRequest> = z
        .object({
            orgId: z.string(),
            rescindUserInvite: components.RescindUserInvite$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                rescindUserInvite: "RescindUserInvite",
            });
        });
}
