/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateUserInviteRequest = {
  orgId: string;
  updateUserInvite: components.UpdateUserInvite;
};

/** @internal */
export type UpdateUserInviteRequest$Outbound = {
  orgId: string;
  UpdateUserInvite: components.UpdateUserInvite$Outbound;
};

/** @internal */
export const UpdateUserInviteRequest$outboundSchema: z.ZodType<
  UpdateUserInviteRequest$Outbound,
  z.ZodTypeDef,
  UpdateUserInviteRequest
> = z.object({
  orgId: z.string(),
  updateUserInvite: z.lazy(() => components.UpdateUserInvite$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    updateUserInvite: "UpdateUserInvite",
  });
});

export function updateUserInviteRequestToJSON(
  updateUserInviteRequest: UpdateUserInviteRequest,
): string {
  return JSON.stringify(
    UpdateUserInviteRequest$outboundSchema.parse(updateUserInviteRequest),
  );
}
