/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../internal/utils";
import { TransportType } from "./transporttype";
import { Expose } from "class-transformer";

/**
 * Connection details for an active process.
 */
export class ExposedPort extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "host" })
    host: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "port" })
    port: number;

    /**
     * Transport type specifies the underlying communication protocol to the exposed port.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transportType" })
    transportType: TransportType;
}
