/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { catchUnrecognizedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { TransportType, TransportType$inboundSchema } from "./transporttype.js";

export const ActiveConnectionInfoStatus = {
  Active: "active",
} as const;
export type ActiveConnectionInfoStatus = OpenEnum<
  typeof ActiveConnectionInfoStatus
>;

export type ActiveConnectionInfo = {
  status: ActiveConnectionInfoStatus;
  /**
   * Transport type specifies the underlying communication protocol to the exposed port.
   */
  transportType: TransportType;
  port: number;
  host: string;
  /**
   * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
   *
   * @remarks
   * Note: error will be returned if `roomId` is not globally unique.
   */
  roomId: string;
};

/** @internal */
export const ActiveConnectionInfoStatus$inboundSchema: z.ZodType<
  ActiveConnectionInfoStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(ActiveConnectionInfoStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const ActiveConnectionInfo$inboundSchema: z.ZodType<
  ActiveConnectionInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ActiveConnectionInfoStatus$inboundSchema,
  transportType: TransportType$inboundSchema,
  port: z.number(),
  host: z.string(),
  roomId: z.string(),
});

export function activeConnectionInfoFromJSON(
  jsonString: string,
): SafeParseResult<ActiveConnectionInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveConnectionInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveConnectionInfo' from JSON`,
  );
}
