/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthConfiguration,
  AuthConfiguration$inboundSchema,
  AuthConfiguration$Outbound,
  AuthConfiguration$outboundSchema,
} from "./authconfiguration.js";
import {
  ServiceConfig,
  ServiceConfig$inboundSchema,
  ServiceConfig$Outbound,
  ServiceConfig$outboundSchema,
} from "./serviceconfig.js";

export type AppConfigWithServiceConfig = {
  serviceConfig?: ServiceConfig | undefined;
  /**
   * Configure [player authentication](https://hathora.dev/docs/backend-integrations/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
   */
  authConfiguration: AuthConfiguration;
  /**
   * Readable name for an application. Must be unique within an organization.
   */
  appName: string;
};

/** @internal */
export const AppConfigWithServiceConfig$inboundSchema: z.ZodType<
  AppConfigWithServiceConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceConfig: ServiceConfig$inboundSchema.optional(),
  authConfiguration: AuthConfiguration$inboundSchema,
  appName: z.string(),
});

/** @internal */
export type AppConfigWithServiceConfig$Outbound = {
  serviceConfig?: ServiceConfig$Outbound | undefined;
  authConfiguration: AuthConfiguration$Outbound;
  appName: string;
};

/** @internal */
export const AppConfigWithServiceConfig$outboundSchema: z.ZodType<
  AppConfigWithServiceConfig$Outbound,
  z.ZodTypeDef,
  AppConfigWithServiceConfig
> = z.object({
  serviceConfig: ServiceConfig$outboundSchema.optional(),
  authConfiguration: AuthConfiguration$outboundSchema,
  appName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppConfigWithServiceConfig$ {
  /** @deprecated use `AppConfigWithServiceConfig$inboundSchema` instead. */
  export const inboundSchema = AppConfigWithServiceConfig$inboundSchema;
  /** @deprecated use `AppConfigWithServiceConfig$outboundSchema` instead. */
  export const outboundSchema = AppConfigWithServiceConfig$outboundSchema;
  /** @deprecated use `AppConfigWithServiceConfig$Outbound` instead. */
  export type Outbound = AppConfigWithServiceConfig$Outbound;
}

export function appConfigWithServiceConfigToJSON(
  appConfigWithServiceConfig: AppConfigWithServiceConfig,
): string {
  return JSON.stringify(
    AppConfigWithServiceConfig$outboundSchema.parse(appConfigWithServiceConfig),
  );
}

export function appConfigWithServiceConfigFromJSON(
  jsonString: string,
): SafeParseResult<AppConfigWithServiceConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppConfigWithServiceConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppConfigWithServiceConfig' from JSON`,
  );
}
