/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ActiveConnectionInfo, ActiveConnectionInfo$ } from "./activeconnectioninfo";
import { StartingConnectionInfo, StartingConnectionInfo$ } from "./startingconnectioninfo";
import * as z from "zod";

/**
 * Connection information to the default port.
 */
export type ConnectionInfo = StartingConnectionInfo | ActiveConnectionInfo;

/** @internal */
export namespace ConnectionInfo$ {
    export type Inbound = StartingConnectionInfo$.Inbound | ActiveConnectionInfo$.Inbound;

    export type Outbound = StartingConnectionInfo$.Outbound | ActiveConnectionInfo$.Outbound;
    export const inboundSchema: z.ZodType<ConnectionInfo, z.ZodTypeDef, Inbound> = z.union([
        StartingConnectionInfo$.inboundSchema,
        ActiveConnectionInfo$.inboundSchema,
    ]);
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectionInfo> = z.union([
        StartingConnectionInfo$.outboundSchema,
        ActiveConnectionInfo$.outboundSchema,
    ]);
}
