/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { Scope, Scope$outboundSchema } from "./scope.js";
import { UserRole, UserRole$outboundSchema } from "./userrole.js";

/**
 * If not defined, the user has Admin access.
 */
export type CreateUserInviteScopes = UserRole | Array<Scope>;

export type CreateUserInvite = {
  /**
   * If not defined, the user has Admin access.
   */
  scopes?: UserRole | Array<Scope> | undefined;
  /**
   * A user's email.
   */
  userEmail: string;
};

/** @internal */
export type CreateUserInviteScopes$Outbound = string | Array<string>;

/** @internal */
export const CreateUserInviteScopes$outboundSchema: z.ZodType<
  CreateUserInviteScopes$Outbound,
  z.ZodTypeDef,
  CreateUserInviteScopes
> = z.union([UserRole$outboundSchema, z.array(Scope$outboundSchema)]);

export function createUserInviteScopesToJSON(
  createUserInviteScopes: CreateUserInviteScopes,
): string {
  return JSON.stringify(
    CreateUserInviteScopes$outboundSchema.parse(createUserInviteScopes),
  );
}

/** @internal */
export type CreateUserInvite$Outbound = {
  scopes?: string | Array<string> | undefined;
  userEmail: string;
};

/** @internal */
export const CreateUserInvite$outboundSchema: z.ZodType<
  CreateUserInvite$Outbound,
  z.ZodTypeDef,
  CreateUserInvite
> = z.object({
  scopes: z.union([UserRole$outboundSchema, z.array(Scope$outboundSchema)])
    .optional(),
  userEmail: z.string(),
});

export function createUserInviteToJSON(
  createUserInvite: CreateUserInvite,
): string {
  return JSON.stringify(
    CreateUserInvite$outboundSchema.parse(createUserInvite),
  );
}
