/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CustomerPortalUrl = {
  returnUrl: string;
};

/** @internal */
export type CustomerPortalUrl$Outbound = {
  returnUrl: string;
};

/** @internal */
export const CustomerPortalUrl$outboundSchema: z.ZodType<
  CustomerPortalUrl$Outbound,
  z.ZodTypeDef,
  CustomerPortalUrl
> = z.object({
  returnUrl: z.string(),
});

export function customerPortalUrlToJSON(
  customerPortalUrl: CustomerPortalUrl,
): string {
  return JSON.stringify(
    CustomerPortalUrl$outboundSchema.parse(customerPortalUrl),
  );
}
