/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type FleetRegionConfig = {
  cloudMinVcpus: number;
};

/** @internal */
export type FleetRegionConfig$Outbound = {
  cloudMinVcpus: number;
};

/** @internal */
export const FleetRegionConfig$outboundSchema: z.ZodType<
  FleetRegionConfig$Outbound,
  z.ZodTypeDef,
  FleetRegionConfig
> = z.object({
  cloudMinVcpus: z.number().int(),
});

export function fleetRegionConfigToJSON(
  fleetRegionConfig: FleetRegionConfig,
): string {
  return JSON.stringify(
    FleetRegionConfig$outboundSchema.parse(fleetRegionConfig),
  );
}
