/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum InvoiceStatus {
    Pending = "pending",
    Paid = "paid",
    Overdue = "overdue",
}

/** @internal */
export const InvoiceStatus$: z.ZodNativeEnum<typeof InvoiceStatus> = z.nativeEnum(InvoiceStatus);
