/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Types of lobbies a player can create.
 *
 * @remarks
 *
 * `private`: the player who created the room must share the roomId with their friends
 *
 * `public`: visible in the public lobby list, anyone can join
 *
 * `local`: for testing with a server running locally
 */
export const LobbyVisibility = {
  Private: "private",
  Public: "public",
  Local: "local",
} as const;
/**
 * Types of lobbies a player can create.
 *
 * @remarks
 *
 * `private`: the player who created the room must share the roomId with their friends
 *
 * `public`: visible in the public lobby list, anyone can join
 *
 * `local`: for testing with a server running locally
 */
export type LobbyVisibility = OpenEnum<typeof LobbyVisibility>;

/** @internal */
export const LobbyVisibility$inboundSchema: z.ZodType<
  LobbyVisibility,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(LobbyVisibility);
/** @internal */
export const LobbyVisibility$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  LobbyVisibility
> = openEnums.outboundSchema(LobbyVisibility);
