/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Region, Region$inboundSchema } from "./region.js";

export type PingEndpoints = {
  port: number;
  host: string;
  region: Region;
};

/** @internal */
export const PingEndpoints$inboundSchema: z.ZodType<
  PingEndpoints,
  z.ZodTypeDef,
  unknown
> = z.object({
  port: z.number(),
  host: z.string(),
  region: Region$inboundSchema,
});

export function pingEndpointsFromJSON(
  jsonString: string,
): SafeParseResult<PingEndpoints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PingEndpoints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PingEndpoints' from JSON`,
  );
}
