/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

/**
 * A plan defines how much CPU and memory is required to run an instance of your game server.
 *
 * @remarks
 *
 * `tiny`: shared core, 1gb memory
 *
 * `small`: 1 core, 2gb memory
 *
 * `medium`: 2 core, 4gb memory
 *
 * `large`: 4 core, 8gb memory
 */
export const PlanName = {
  Tiny: "tiny",
  Small: "small",
  Medium: "medium",
  Large: "large",
} as const;
/**
 * A plan defines how much CPU and memory is required to run an instance of your game server.
 *
 * @remarks
 *
 * `tiny`: shared core, 1gb memory
 *
 * `small`: 1 core, 2gb memory
 *
 * `medium`: 2 core, 4gb memory
 *
 * `large`: 4 core, 8gb memory
 */
export type PlanName = OpenEnum<typeof PlanName>;

/** @internal */
export const PlanName$inboundSchema: z.ZodType<
  PlanName,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(PlanName),
    z.string().transform(catchUnrecognizedEnum),
  ]);
/** @internal */
export const PlanName$outboundSchema: z.ZodType<
  PlanName,
  z.ZodTypeDef,
  PlanName
> = z.union([
  z.nativeEnum(PlanName),
  z.string().and(z.custom<Unrecognized<string>>()),
]);
