/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A plan defines how much CPU and memory is required to run an instance of your game server.
 *
 * @remarks
 *
 * `tiny`: shared core, 1gb memory
 *
 * `small`: 1 core, 2gb memory
 *
 * `medium`: 2 core, 4gb memory
 *
 * `large`: 4 core, 8gb memory
 */
export enum PlanName {
    Tiny = "tiny",
    Small = "small",
    Medium = "medium",
    Large = "large",
}

/** @internal */
export const PlanName$: z.ZodNativeEnum<typeof PlanName> = z.nativeEnum(PlanName);
