/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type RescindUserInvite = {
  /**
   * A user's email.
   */
  userEmail: string;
};

/** @internal */
export type RescindUserInvite$Outbound = {
  userEmail: string;
};

/** @internal */
export const RescindUserInvite$outboundSchema: z.ZodType<
  RescindUserInvite$Outbound,
  z.ZodTypeDef,
  RescindUserInvite
> = z.object({
  userEmail: z.string(),
});

export function rescindUserInviteToJSON(
  rescindUserInvite: RescindUserInvite,
): string {
  return JSON.stringify(
    RescindUserInvite$outboundSchema.parse(rescindUserInvite),
  );
}
