/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * The allocation status of a room.
 *
 * @remarks
 *
 * `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
 *
 * `active`: ready to accept connections
 *
 * `destroyed`: all associated metadata is deleted
 */
export const RoomStatus = {
  Scheduling: "scheduling",
  Active: "active",
  Destroyed: "destroyed",
} as const;
/**
 * The allocation status of a room.
 *
 * @remarks
 *
 * `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
 *
 * `active`: ready to accept connections
 *
 * `destroyed`: all associated metadata is deleted
 */
export type RoomStatus = OpenEnum<typeof RoomStatus>;

/** @internal */
export const RoomStatus$inboundSchema: z.ZodType<
  RoomStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(RoomStatus);
