/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { RoomStatus, RoomStatus$inboundSchema } from "./roomstatus.js";

/**
 * Metadata on an allocated instance of a room.
 */
export type RoomWithoutAllocationsCurrentAllocation = {
  unscheduledAt: Date | null;
  scheduledAt: Date;
  /**
   * System generated unique identifier to a runtime instance of your game server.
   */
  processId: string;
  /**
   * System generated unique identifier to an allocated instance of a room.
   */
  roomAllocationId: string;
};

export type RoomWithoutAllocations = {
  currentAllocation: RoomWithoutAllocationsCurrentAllocation | null;
  /**
   * The allocation status of a room.
   *
   * @remarks
   *
   * `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
   *
   * `active`: ready to accept connections
   *
   * `destroyed`: all associated metadata is deleted
   */
  status: RoomStatus;
  roomConfig?: string | null | undefined;
  /**
   * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
   *
   * @remarks
   * Note: error will be returned if `roomId` is not globally unique.
   */
  roomId: string;
  /**
   * System generated unique identifier for an application.
   */
  appId: string;
};

/** @internal */
export const RoomWithoutAllocationsCurrentAllocation$inboundSchema: z.ZodType<
  RoomWithoutAllocationsCurrentAllocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  unscheduledAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  scheduledAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  processId: z.string(),
  roomAllocationId: z.string(),
});

export function roomWithoutAllocationsCurrentAllocationFromJSON(
  jsonString: string,
): SafeParseResult<
  RoomWithoutAllocationsCurrentAllocation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RoomWithoutAllocationsCurrentAllocation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RoomWithoutAllocationsCurrentAllocation' from JSON`,
  );
}

/** @internal */
export const RoomWithoutAllocations$inboundSchema: z.ZodType<
  RoomWithoutAllocations,
  z.ZodTypeDef,
  unknown
> = z.object({
  currentAllocation: z.nullable(
    z.lazy(() => RoomWithoutAllocationsCurrentAllocation$inboundSchema),
  ),
  status: RoomStatus$inboundSchema,
  roomConfig: z.nullable(z.string()).optional(),
  roomId: z.string(),
  appId: z.string(),
});

export function roomWithoutAllocationsFromJSON(
  jsonString: string,
): SafeParseResult<RoomWithoutAllocations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoomWithoutAllocations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoomWithoutAllocations' from JSON`,
  );
}
