/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RoomAllocation,
  RoomAllocation$inboundSchema,
  RoomAllocation$Outbound,
  RoomAllocation$outboundSchema,
} from "./roomallocation.js";
import {
  RoomStatus,
  RoomStatus$inboundSchema,
  RoomStatus$outboundSchema,
} from "./roomstatus.js";

/**
 * Metadata on an allocated instance of a room.
 */
export type CurrentAllocation = {
  unscheduledAt: Date | null;
  scheduledAt: Date;
  /**
   * System generated unique identifier to a runtime instance of your game server.
   */
  processId: string;
  /**
   * System generated unique identifier to an allocated instance of a room.
   */
  roomAllocationId: string;
};

/**
 * A room object represents a game session or match.
 */
export type Room = {
  currentAllocation: CurrentAllocation | null;
  /**
   * The allocation status of a room.
   *
   * @remarks
   *
   * `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
   *
   * `active`: ready to accept connections
   *
   * `destroyed`: all associated metadata is deleted
   */
  status: RoomStatus;
  allocations: Array<RoomAllocation>;
  roomConfig?: string | null | undefined;
  /**
   * Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
   *
   * @remarks
   * Note: error will be returned if `roomId` is not globally unique.
   */
  roomId: string;
  /**
   * System generated unique identifier for an application.
   */
  appId: string;
};

/** @internal */
export const CurrentAllocation$inboundSchema: z.ZodType<
  CurrentAllocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  unscheduledAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  scheduledAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  processId: z.string(),
  roomAllocationId: z.string(),
});

/** @internal */
export type CurrentAllocation$Outbound = {
  unscheduledAt: string | null;
  scheduledAt: string;
  processId: string;
  roomAllocationId: string;
};

/** @internal */
export const CurrentAllocation$outboundSchema: z.ZodType<
  CurrentAllocation$Outbound,
  z.ZodTypeDef,
  CurrentAllocation
> = z.object({
  unscheduledAt: z.nullable(z.date().transform(v => v.toISOString())),
  scheduledAt: z.date().transform(v => v.toISOString()),
  processId: z.string(),
  roomAllocationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CurrentAllocation$ {
  /** @deprecated use `CurrentAllocation$inboundSchema` instead. */
  export const inboundSchema = CurrentAllocation$inboundSchema;
  /** @deprecated use `CurrentAllocation$outboundSchema` instead. */
  export const outboundSchema = CurrentAllocation$outboundSchema;
  /** @deprecated use `CurrentAllocation$Outbound` instead. */
  export type Outbound = CurrentAllocation$Outbound;
}

export function currentAllocationToJSON(
  currentAllocation: CurrentAllocation,
): string {
  return JSON.stringify(
    CurrentAllocation$outboundSchema.parse(currentAllocation),
  );
}

export function currentAllocationFromJSON(
  jsonString: string,
): SafeParseResult<CurrentAllocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentAllocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentAllocation' from JSON`,
  );
}

/** @internal */
export const Room$inboundSchema: z.ZodType<Room, z.ZodTypeDef, unknown> = z
  .object({
    currentAllocation: z.nullable(
      z.lazy(() => CurrentAllocation$inboundSchema),
    ),
    status: RoomStatus$inboundSchema,
    allocations: z.array(RoomAllocation$inboundSchema),
    roomConfig: z.nullable(z.string()).optional(),
    roomId: z.string(),
    appId: z.string(),
  });

/** @internal */
export type Room$Outbound = {
  currentAllocation: CurrentAllocation$Outbound | null;
  status: string;
  allocations: Array<RoomAllocation$Outbound>;
  roomConfig?: string | null | undefined;
  roomId: string;
  appId: string;
};

/** @internal */
export const Room$outboundSchema: z.ZodType<Room$Outbound, z.ZodTypeDef, Room> =
  z.object({
    currentAllocation: z.nullable(
      z.lazy(() => CurrentAllocation$outboundSchema),
    ),
    status: RoomStatus$outboundSchema,
    allocations: z.array(RoomAllocation$outboundSchema),
    roomConfig: z.nullable(z.string()).optional(),
    roomId: z.string(),
    appId: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Room$ {
  /** @deprecated use `Room$inboundSchema` instead. */
  export const inboundSchema = Room$inboundSchema;
  /** @deprecated use `Room$outboundSchema` instead. */
  export const outboundSchema = Room$outboundSchema;
  /** @deprecated use `Room$Outbound` instead. */
  export type Outbound = Room$Outbound;
}

export function roomToJSON(room: Room): string {
  return JSON.stringify(Room$outboundSchema.parse(room));
}

export function roomFromJSON(
  jsonString: string,
): SafeParseResult<Room, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Room$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Room' from JSON`,
  );
}
