/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SetLobbyStateParams = {
    /**
     * JSON blob to store metadata for a room. Must be smaller than 1MB.
     */
    state?: any | undefined;
};

/** @internal */
export namespace SetLobbyStateParams$ {
    export const inboundSchema: z.ZodType<SetLobbyStateParams, z.ZodTypeDef, unknown> = z
        .object({
            state: z.any().optional(),
        })
        .transform((v) => {
            return {
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });

    export type Outbound = {
        state?: any | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetLobbyStateParams> = z
        .object({
            state: z.any().optional(),
        })
        .transform((v) => {
            return {
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });
}
